[package]
name = "quad"
version = "0.1.0"
description = "Pure-Rust command line quadratic equation solver"
license = "GPL-3.0+"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
